## intellipat tutorial #######

In [1]:
# what is data science? data science is applying science on data for it to talk to us, and it includes techniques such as data visualization,
# data manipulation, statistical analysis and machine learning.
# data visualization: science and design combined in a meaningful way to interpret the data through graphs and plots
# data manipulation: is used to change the raw data and make it more organised, so that finding insights into the data becomes easy
# statistical analysis: Applying maths to data to understand the structure of data
# machine learning: the art of training a machine to learn and understand the features of an object


#LIFE CYCLE OF DATA SCIENCE:
# data acquisition---data pre-processing---model building---pattern evaluation---knowledge representation
# data acquisition: getting data from different sources, storing it in a location(data warehouse), and then select the data needed(target data)
# data pre-processing: applying processes such as normalization and aggregation
# model-building: applying scientific algorithm such as linear regression, k-means and random forest to the pre-processed data
# pattern evaluation
# knowledge representation: using graphs and plots

# APPLICATION OF DATA SCIENCE
# chat bots, self driving cars, sentiments analysis(retail industries, elections), image tagging(facebook)



# numpy tutorial ###

In [2]:
  # CREATE NUMPY ARRAYS
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([20, 30, 40, 50])
print(a)
print(b)

[1 2 3 4 5]
[20 30 40 50]


In [25]:
b[1] = 9000
b[1]

9000

In [57]:
c = np.array([[1,2,3,4,5,6],[20,10,30,40,50,30], [0, 3, 4, 5, 6,7]])
a[1:2]
a[1:3]
a[:4]
c[:1]

array([[1, 2, 3, 4, 5, 6]])

In [76]:
np.zeros((5,6))
np.arange(10,200,5)
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [81]:
np.full((3,10),20) #(row, column, number to fill up)

array([[20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]])

In [89]:
np.random.random((4,10))

array([[0.38965773, 0.25523713, 0.0635973 , 0.00499947, 0.95099447,
        0.14411535, 0.51596622, 0.76366771, 0.37669685, 0.20765976],
       [0.19634847, 0.57948504, 0.30974081, 0.59834778, 0.63242687,
        0.84773878, 0.38735612, 0.22942415, 0.92184274, 0.14822343],
       [0.90845841, 0.0580353 , 0.73926766, 0.71744493, 0.88736312,
        0.73739443, 0.18108389, 0.14205829, 0.35234833, 0.21489961],
       [0.17419631, 0.855532  , 0.51243007, 0.34971183, 0.61684749,
        0.10545178, 0.37620369, 0.83639752, 0.51140429, 0.65659994]])

# ND ARRAY SHAPE

In [92]:
chibuzor = np.array([[2,3,4,5,6],[10,20,30,40,50],[20,50,60,70,90]])
chibuzor

array([[ 2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50],
       [20, 50, 60, 70, 90]])

In [93]:
chibuzor.shape

(3, 5)

In [123]:
chibuzor.shape = (5,3)
chibuzor.ndim

2

In [111]:
chibuzor.shape[0]#ie shape(5,3)  5=0, 3=1
chibuzor
chibuzor.shape[1]

3

In [126]:
chibuzor.size
chibuzor.dtype
#chibuzor

dtype('int32')

In [128]:
chibuzor = np.linspace(10,100,10)
print(chibuzor)
print(chibuzor.dtype)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
float64


## MATHS IN NUMPY

In [129]:
chibuzor = np.sum([20,30,40,50])
chibuzor

140

In [131]:
a,b,c,d=20,30,40,2000
np.sum([a,b,c,d])

2090

In [134]:
np.sum([[2,3,4,5],[10,30,20,50]], axis=0)
np.sum([[2,3,4,5],[10,30,20,50]], axis=1)

array([ 14, 110])

In [162]:
a=[1,2,3]
b=[2,5,7]
print(np.subtract(a,b))


[-1 -3 -4]


In [231]:
# a=np.array([5,20])
# b=np.array([10,20])
# print(a)
# print(b)
# np.subtract(a,b)
# x = np.sum([a,b], axis=0)
# y = np.sum([a,b], axis=1)
# print(x)
# print(y)

a = np.array([[5,20],[4,8]])
b = np.array([[10,20],[2,6]])
print(a)
print(b)
np.subtract(a,b)
print(np.sum([a,b], axis=0))
print(np.sum([a,b], axis=1))

[[ 5 20]
 [ 4  8]]
[[10 20]
 [ 2  6]]
[[15 40]
 [ 6 14]]
[[ 9 28]
 [12 26]]


In [199]:
a=np.array([10, 40])
b=np.array([5,8])
print(a)
print(b)

[10 40]
[5 8]


In [204]:
print(np.divide(a,b))

[2. 5.]


In [205]:
print(np.multiply(a,b))

[ 50 320]


In [209]:
print(np.exp(a))

[2.20264658e+04 2.35385267e+17]


In [210]:
print(np.exp(b))

[ 148.4131591  2980.95798704]


In [211]:
print(np.sqrt(a))

[3.16227766 6.32455532]


In [212]:
print(np.sqrt(b))

[2.23606798 2.82842712]


In [213]:
print(np.sin(a))

[-0.54402111  0.74511316]


In [214]:
print(np.sin(b))

[-0.95892427  0.98935825]


In [215]:
print(np.log(a))

[2.30258509 3.68887945]


In [216]:
print(np.log(b))

[1.60943791 2.07944154]


## ARRAY COMPARISON

In [220]:
a=[2,3,4]
b=[2,1,5]
c=[2,3,5]
d=[2,3,4]
print(np.equal(a,b))
print(np.equal(a,c))
print(np.array_equal(a,d))

[ True False False]
[ True  True False]
True


## AGGREGATE FUNCTION

In [223]:
a=([2,3,4],[2,3,5])
b=[2,1,5]
c=[2,3,5]
d=[2,3,4]
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.corrcoef(a))

19
2
5
3.1666666666666665
3.0
1.0671873729054748
[[1.         0.98198051]
 [0.98198051 1.        ]]


## CONCEPT OF BROADCASTING

In [233]:
a=np.array([[1,2,3,4],[2,4,6,7]])
b=np.array([4,3,2,7])
print(a)
print(b)
print(np.subtract(a,b))
print(np.sum([a,b]))

[[1 2 3 4]
 [2 4 6 7]]
[4 3 2 7]
[[-3 -1  1 -3]
 [-2  1  4  0]]
[[ 5  5  5 11]
 [ 6  7  8 14]]


## INDEXING AND SLICING IN PYTHON

In [34]:
a = np.array([[1,2,3,4,5],[2,5,7,9,1],[3,0,7,6,5]])
#print(a)
#print(a[1:,])
# print(a[:1])
print(a[:2,2:])
#print(a[2:,:3])

[[3 4 5]
 [7 9 1]]


## ARRAY MANIPULATION IN PYTHON

In [14]:
a = ([1,2,4],[2,3,4])
b = ([2,4,4],[5,6,7])
print("concatenation.......")
print(np.concatenate((a,b), axis=0))
print("vertical stacking......")
print(np.vstack((a,b)))
print("horizontal stacking......")
print(np.hstack((a,b)))
print("column_stacking......")
print(np.column_stack((a,b)))
print(np.concatenate(([a,b]), axis=0))
print(np.concatenate(([a,b]), axis=1))



concatenation.......
[[1 2 4]
 [2 3 4]
 [2 4 4]
 [5 6 7]]
vertical stacking......
[[1 2 4]
 [2 3 4]
 [2 4 4]
 [5 6 7]]
horizontal stacking......
[[1 2 4 2 4 4]
 [2 3 4 5 6 7]]
column_stacking......
[[1 2 4 2 4 4]
 [2 3 4 5 6 7]]
[[1 2 4]
 [2 3 4]
 [2 4 4]
 [5 6 7]]
[[1 2 4 2 4 4]
 [2 3 4 5 6 7]]


In [22]:
x=np.arange(16.0).reshape(4,4)
print(x,"\n\n")
print(np.hsplit(x, 2), "\n\n")
print(np.hsplit(x, np.array([3,6])))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]] 


[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])] 


[array([[ 0.,  1.,  2.],
       [ 4.,  5.,  6.],
       [ 8.,  9., 10.],
       [12., 13., 14.]]), array([[ 3.],
       [ 7.],
       [11.],
       [15.]]), array([], shape=(4, 0), dtype=float64)]
